@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
'skinparam linetype ortho
'skinparam linetype polyline

'Includes
!include https://raw.githubusercontent.com/egrpy/UUMF/main/50%20Sales%20System%20-%20Example/00%20Configurations/10%20Configurations.puml
$dictionary_include()

title UC Supplier Search - Classes (System Analysis)
Package $systemName {
    $classSupplierSearch()
    $classSuppliers()
}

$uumf_associtarion($class1 = "supplierSearch", $class2 = "suppliers", $type="-->")

@enduml