@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
'skinparam linetype ortho
'skinparam linetype polyline

'----------------------------
'UI elements summary
'----------------------------
  'supplierSearch <<window>>
    'label: lb_searchCritera
    'Field: ef_searchCritera
    'Button: bt_search
    'Button: bt_exit
'DataLAyer
  'entity: supplier
'OS
  'clipboard
'----------------------------

'Includes
!include https://raw.githubusercontent.com/egrpy/UUMF/main/50%20Sales%20System%20-%20Example/00%20Configurations/10%20Configurations.puml
$uumf_include()
$dictionary_include()

title UC Supplier Search (System Design)

Package $systemName {
  Package "UI Supplier Search" {
    'UI Goal
    note as UIGoal
      La ventana Supplier Search está diseñada para
      permitir a los usuarios la búsqueda de proveedores
      por cualquiera de los atributos de suppliers.
    end note

    'Containers
    $supplierSearch()

    'Data Models

    'Labels
    $uumf_label($name = "lb_searchCriteria", $labelDisplay = "Search Criteria")

    'Edit Fields
    $uumf_editField($name = "ef_searchCriteria", $dataType = "string", $initialValue = "null")

    'Buttons
    $uumf_button($name = "btSearch", $labelDisplay = "Exit", $activate = "TRUE", $initialization = "FALSE")
    $defClassEnd()

    $uumf_button($name = "btExit", $labelDisplay = "Exit", $activate = "TRUE", $initialization = "FALSE")
    $defClassEnd()

    'Relationships: Internal at UI package
    $uumf_associtarion($class1 = "supplierSearch", $class2 = "lb_searchCriteria", $type="*-l-")
    $uumf_associtarion($class1 = "supplierSearch", $class2 = "ef_searchCriteria", $type="*--")
    $uumf_associtarion($class1 = "supplierSearch", $class2 = "btSearch", $type="*--")
    $uumf_associtarion($class1 = "supplierSearch", $class2 = "btExit", $type="*--")
    $uumf_associtarion($class1 = "lb_searchCriteria", $class2 = "ef_searchCriteria", $type="->") :Asociado con
  }
  
  package DataLayer {
    $classSuppliers()
  }
  $uumf_associtarion($class1 = "supplierSearch", $class2 = "suppliers", $type="-d->")

  package "OS" {
    $clipboard()
  }
  $uumf_associtarion($class1 = "supplierSearch", $class2 = "clipboard", $type="-l->")
}

@enduml