@startuml
'--------------------------------------------------------------------------------
'Script for Class Declaration
'--------------------------------------------------------------------------------
!include https://raw.githubusercontent.com/egrpy/SqlUMLSpec/main/sqlUMLSpecFunctions.puml

'--------------------------------------------------------------------------------
'Declare Label Class
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_label($labelName = "LabelName")
  $defClass($classType = "", $name = $labelName, $stereotype = "<<label>>", $color = "")
    $defClassAttribute($visibility = "-", $name = "label", $dataType = "string")
    + actionsWhenDisplay() :void
  $defClassEnd()
!endprocedure

'--------------------------------------------------------------------------------
'Declare Button Class 
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_button($labelName = "LabelName")
  $defClass($classType = "", $name = $labelName, $stereotype = "<<button>>", $color = "")
    $defClassAttribute($visibility = "-", $name = "label", $dataType = "string")
    + actionsWhenDisplay() :void
    + clicked() :void
  $defClassEnd()
!endprocedure

'--------------------------------------------------------------------------------
'Declare Edit Field Class 
'--------------------------------------------------------------------------------
'Falta agregar default value
!unquoted procedure $uumf_editField($fieldName = "FieldName", $dataType = "T")
  $defClass($classType = "", $name = $fieldName, $stereotype = "<<editField>>", $color = "")
    $defClassAttribute($visibility = "-", $name="value", $dataType = $dataType)
    + actionsWhenDisplay() :void
    + setValue(value: T) : void
    + getValue() : T
  $defClassEnd()
!endprocedure

'--------------------------------------------------------------------------------
'Declare Window Class 
'--------------------------------------------------------------------------------
'Falta agregar default value
!unquoted procedure $uumf_window($windowName = "WindowName", $title = "Title of Window")
  $defClass($classType = "", $name = $windowName, $stereotype = "<<window>>", $color = "")
    $defClassAttribute($visibility = "-", $name = "title", $dataType = "string", $calculate = "default =" + $title, $constraint = "xxx")
    + actionsWhenOpen() :void
    + actionsWhenClose() : void
  $defClassEnd()
!endprocedure


@enduml
