@startuml
'--------------------------------------------------------------------------------
'Script for Class Declaration
'--------------------------------------------------------------------------------
!include https://raw.githubusercontent.com/egrpy/SqlUMLSpec/main/sqlUMLSpecFunctions.puml

'--------------------------------------------------------------------------------
'Declare Label Class
'--------------------------------------------------------------------------------
!unquoted function defLabel($LabelName="")
  !local $aux = ""
  !aux = $defClass($classType="", $name=$LabelName, $stereotype="<<label>>")
  !aux = $defClassAttribute($visibility = "-", $name="label", $dataType = ":string")
  !aux = $defClassEnd()
  !return $aux
!endfunction

'--------------------------------------------------------------------------------
'Example
'--------------------------------------------------------------------------------
$defClass($classType="abstract", $name="ClassName", $stereotype="<<temporary>>")
  $defClassAttribute($visibility = "-", $name="", $dataType = "T")
  $defClassSetWhere($logicOper="AND", $condition="")
$defClassEnd()

@enduml
