@startuml
'--------------------------------------------------------------------------------
'Script for Class Declaration
'--------------------------------------------------------------------------------
!include https://raw.githubusercontent.com/egrpy/SqlUMLSpec/main/sqlUMLSpecFunctions.puml

'--------------------------------------------------------------------------------
'Declare Label Class
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_Label($labelName = "LabelName")
  $defClass($classType = "", $name = $labelName, $stereotype = "<<label>>", $color = "")
  $defClassAttribute($visibility = "-", $name = "label", $dataType = "string")
  $defClassEnd()
!endprocedure

'--------------------------------------------------------------------------------
'Declare Button Class 
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_button($labelName = "LabelName")
  $defClass($classType = "", $name = $labelName, $stereotype = "<<button>>", $color = "")
  $defClassAttribute($visibility = "-", $name = "label", $dataType = "string")
  $defClassEnd()
!endprocedure

'--------------------------------------------------------------------------------
'Declare Edit Field Class 
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_editField($fieldName = "FieldName", $dataType = "T", $value = "")
  $defClass($classType = "", $name = $fieldName, $stereotype = "<<editField>>", $color = "")
  $defClassAttribute($visibility = "-", $name="value", $dataType = $dataType)
  $defClassEnd()
!endprocedure

@enduml
