@startuml
!procedure $class_suppliers()
    class suppliers <<entity>> {
    - idSupplier :integer {PK} {not null}
    - name :string {not null}
    - address :string
    - email :string
    + insert(idSupplier :integer, name :string, address :string, email :string) :boolean
    + update(idSupplier :integer, name :string, address :string, email :string) :boolean
    + delete(idSupplier :integer) :boolean
    + getsupplier(idSupplier :integer, name :string, address :string, email :string) recordSupplier
    }
!endprocedure
'Testing
'$class_suppliers()
@enduml