@startuml
'--------------------------------------------------------------------------------
'Script for Class Declaration
'--------------------------------------------------------------------------------
!include https://raw.githubusercontent.com/egrpy/SqlUMLSpec/main/sqlUMLSpecFunctions.puml

'--------------------------------------------------------------------------------
'Declare Label Class
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_label($name = "labelName", $labelDisplay = "Label Display")
  !local $labelName = $name

  !if ($labelName == "" || $labelName == "labelName")
    !$labelName = $textColor("labelName", "Red")
  !endif

  'Create a class
  $defClass($classType = "", $name = $labelName, $stereotype = "<<label>>", $color = "")
    $defClassAttribute($visibility = "-", $name = "label", $dataType = "string", $defaultValue = $labelDisplay)
    + initialization() :void
  $defClassEnd()
!endprocedure
'--------------------------------------------------------------------------------
'Declare Button Class 
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_button($name = "buttonName", $labelDisplay = "Label Display", $activate="FALSE", $initialization="FALSE")
  !local $buttonName = $name

  !if ($buttonName == "" || $buttonName == "buttonName")
    !$buttonName = $textColor("buttonName", "Red")
  !endif

  'Create a class
  $defClass($classType = "", $name = $buttonName, $stereotype = "<<button>>", $color = "")
    $defClassAttribute($visibility = "-", $name = "label", $dataType = "string", $defaultValue = $labelDisplay)
    !if ($activate == "TRUE")
      + activate() :void
    !endif
    !if ($initialization == "TRUE")
      + initialization() :void
    !endif
    + clicked() :void
  'Need $defClassEnd() or } to close class definition
!endprocedure

'--------------------------------------------------------------------------------
'Declare Edit Field Class 
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_editField($name = "fieldName", $dataType = "T", $initialValue = "")
  !local $fieldName = $name
  !local $fieldDataType = $dataType

  !if ($fieldName == "" || $fieldName == "fieldName")
    !$fieldName = $textColor("fieldName", "Red")
  !endif

  'Create a class
  $defClass($classType = "", $name = $fieldName, $stereotype = "<<editField>>", $color = "")
    $defClassAttribute($visibility = "-", $name = "value", $dataType = $fieldDataType, $defaultValue = $initialValue)
    + initialization() :void
    + setValue(value: T) : void
    + getValue() : T
  $defClassEnd()
!endprocedure
'--------------------------------------------------------------------------------
'Declare Window Class 
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_window($name = "WindowName", $title = "Title", $initialization = "FALSE")
'This procedure generate the class definition and the principal attribute.
'To complete the definition, required otheres attributes and operations, if is necesary.
  !local $windowName = $name

  !if ($windowName == "" || $windowName == "WindowName")
    !$windowName = $textColor("windowName", "Red")
  !endif

  $defClass($classType = "", $name = $windowName, $stereotype = "<<window>>", $color = "")
    $defClassAttribute($visibility = "-", $name = "title", $dataType = "string", $defaultValue = $title)
    !if ($initialization == "TRUE")
      + initialization() :void
    !endif
  'Need $defClassEnd() or } to close class definition  
!endprocedure
'--------------------------------------------------------------------------------
'Declare WebPage Class 
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_webPage($name = "WebPageName", $title = "Title", $initialization = "FALSE")
'This procedure generate the class definition and the principal attribute.
'To complete the definition, required otheres attributes and operations, if is necesary.
  !local $webPageName = $name

  !if ($webPageName == "" || $webPageName == "WebPageName")
    !$webPageName = $textColor("webPageName", "Red")
  !endif

  $defClass($classType = "", $name = $webPageName, $stereotype = "<<webPage>>", $color = "")
    $defClassAttribute($visibility = "-", $name = "title", $dataType = "string", $defaultValue = $title)
    !if ($initialization == "TRUE")
      + initialization() :void
    !endif
  'Need $defClassEnd() or } to close class definition  
!endprocedure

'--------------------------------------------------------------------------------
'Declare Data Control
'--------------------------------------------------------------------------------
!procedure $uumf_recordLayout()
  class recordLayout <<enumeration>> {
      -form
      -grid
      -reportFreeForm
      -reportTabular
      -reportGrouped
      -reportGraphic
  }
!endprocedure

'--------------------------------------------------------------------------------
'Declare Relationships
'--------------------------------------------------------------------------------
!procedure $uumf_association($class1 = "A", $class2 = "B", $type="-->")
  $class1 $type $class2
!endprocedure

'--------------------------------------------------------------------------------
'Declare Data Model
'--------------------------------------------------------------------------------
!unquoted procedure $uumf_dataModel($name = "dataModelName", $recordlayout="form")
  !local $dataModelName = $name
  !local $lcolor = ""

  !if ($dataModelName == "" || $dataModelName == "dataModelName")
    !$dataModelName = $textColor("dataModelName", "Red")
    !$lcolor = "##[bold]red"
  !endif

  !if ($recordlayout == "form") || ($recordlayout == "grid") || ($recordlayout == "reportFreeForm") || ($recordlayout == "reportTabular") || ($recordlayout == "reportGrouped")
    !$recordlayout = "<<" + $recordlayout + ">>"  
  !else
    !$recordlayout = "<<layoutError>>"
    !$lcolor = "##[bold]red"
  !endif

  $defClass($classType = "", $name = $dataModelName, $stereotype = $recordlayout, $color = $lcolor)

!endprocedure

'--------------------------------------------------------------------------------
'Declare Note
'--------------------------------------------------------------------------------
!procedure uumf_GUINote($name, $goalArray, $delimiter)
    !$list = %splitstr($goalArray, $delimiter)
    note as $name
      !foreach $item in $list
          $item
      !endfor
    end note
!endprocedure
'-----------------------------------------------------------------

@enduml
