@startuml

!$systemName = '"Product Management System 2"'

!unquoted procedure $uumf_include()
    !include https://raw.githubusercontent.com/egrpy/UUMF/main/02%20Framework/uumf_defClass.puml
!endprocedure

!unquoted procedure $SqlUMLSpec_include()
    !include https://raw.githubusercontent.com/egrpy/SqlUMLSpec/main/sqlUMLSpecFunctions.puml
!endprocedure

!unquoted procedure $dictionary_include()
    !include https://raw.githubusercontent.com/egrpy/UUMF/main/50%20Sales%20System%20-%20Example/00%20Configurations/15%20DictionaryProyect.puml
!endprocedure

@enduml