@startuml

!unquoted procedure $uumf_include()
    !include https://raw.githubusercontent.com/egrpy/UUMF/main/02%20Framework/uumf_defClass.puml
!endprocedure

!unquoted procedure $SqlUMLSpec_include()
    !include https://raw.githubusercontent.com/egrpy/SqlUMLSpec/main/sqlUMLSpecFunctions.puml
!endprocedure

!unquoted procedure $dictionary_include()
    !include /Users/egr/Projects/Plantuml/UUMF/UUMF/50 Sales System - Example/00 Configurations/15 DiccionarioProyecto.puml
!endprocedure

@enduml