@startuml
'This script contain the class defintion for a specific case.

!include https://raw.githubusercontent.com/egrpy/UUMF/main/02%20Framework/uumf_defClass.puml

'-----------------------------------------------------------------------------------------------------------
'Analysis Classes
'-----------------------------------------------------------------------------------------------------------
!unquoted procedure $classSuppliers()
    class suppliers <<entity>> {
    - idSupplier :integer {PK} {not null}
    - name :string {not null}
    - address :string
    - email :string
    + insert(idSupplier :integer, name :string, address :string, email :string) :boolean
    + update(idSupplier :integer, name :string, address :string, email :string) :boolean
    + delete(idSupplier :integer) :boolean
    + getsupplier(idSupplier :integer, name :string, address :string, email :string) recordSupplier
    }
!endprocedure

!unquoted procedure $classSuppliersMaintenance()
    class supplierMaintenance <<Boundary>> {
    }
!endprocedure

'-----------------------------------------------------------------------------------------------------------
'Supplier Maintenance
'-----------------------------------------------------------------------------------------------------------
!unquoted procedure $supplierMaintenance()
    $uumf_window($name = "supplierMaintenance", $title = "Supplier Maintenance", $initialization="TRUE")
        +open()
    $defClassEnd()
!endprocedure

!unquoted procedure $btSave()
    $uumf_button($name = "btSave", $labelDisplay = "Save", $activate = "TRUE", $initialization = "FALSE")
    $defClassEnd()
!endprocedure

!unquoted procedure $btDelete()
    $uumf_button($name = "btDelete", $labelDisplay = "Delete", $activate = "TRUE", $initialization = "FALSE")
    $defClassEnd()
!endprocedure

!unquoted procedure $btExit()
    $uumf_button($name = "btExit", $labelDisplay = "Exit", $activate = "TRUE", $initialization = "FALSE")
    $defClassEnd()
!endprocedure

!unquoted procedure $dmSuppliers()
    $uumf_dataModel($name = "dmSupplier", $recordlayout="form")
      '$defClassAttribute($visibility,  $name,          $dataType,  $defaultValue,  $label,         $pk,        $unique,    $required,  $readOnly   $hidden,    $calculate,     $format,        $pattern,   $constraint)
      $defClassAttribute("+",           "id",           "integer",  "1",            "Id",           "FALSE",    "TRUE",     "TRUE",     "FALSE",    "FALSE",    "max(id + 1)",  "##",           "",         "id > 0")
      $defClassAttribute("+",           "idSupplier",   "integer",  "",             "Id Supplier",  "TRUE",     "TRUE",     "TRUE",     "FALSE",    "FALSE",    "",             "######",       "",         "")
      $defClassAttribute("+",           "name",         "string",   "",             "Name",         "FALSE",    "FALSE",    "TRUE",     "FALSE",    "FALSE",    "",             "Upper Case",   "",         "")
      $defClassAttribute("+",           "address",      "string",   "",             "Address",      "FALSE",    "FALSE",    "TRUE",     "FALSE",    "FALSE",    "",             "Upper Case",   "",         "")
      $defClassAttribute("+",           "email",        "string",   "",             "email",        "FALSE",    "FALSE",    "TRUE",     "FALSE",    "FALSE",    "",             "email format", "",         "")      
      + setidSupplier()
      + getidSuppplier()
      + setrecordSupplier()
      + setdataRequiered()
      + validate()
      + validateBeforeSave(recordSupplier) boolean
      + save()
      + delete()
      + insertRow() :void
    $defClassEnd()
!endprocedure

@enduml

'-----------------------------------------------------------------------------------------------------------
'Supplier Search
'-----------------------------------------------------------------------------------------------------------
!unquoted procedure $supplierSearch()
    $uumf_window($name = "supplierSearch", $title = "Supplier Search", $initialization="TRUE")
        +open()
    $defClassEnd()
!endprocedure
