@startuml
'This script contain the class defintion for a specific case.

!include https://raw.githubusercontent.com/egrpy/UUMF/main/uumf_defClass.puml


!unquoted procedure $SupplierMaintenance()
    $uumf_window($name = "SupplierMaintenance", $title = "Supplier Maintenance", $operInitialization="TRUE")
        +open()
    $defClassEnd()
!endprocedure


!unquoted procedure $dsSuppliers()
    
!endprocedure

!unquoted procedure $btSave()
    
!endprocedure

!unquoted procedure $btDelete()
    
!endprocedure

!unquoted procedure $btExit()
    
!endprocedure

$uumf_button($name = "btSave", $labelDisplay = "Save")
$uumf_button($name = "btDelete", $labelDisplay = "Delete")
$uumf_button($name = "btExit", $labelDisplay = "Exit")


@enduml