@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
'skinparam linetype ortho
'skinparam linetype polyline

'Includes
!include https://raw.githubusercontent.com/egrpy/UUMF/main/50%20Sales%20System%20-%20Example/00%20Configurations/10%20Configurations.puml
$uumf_include()
$dictionary_include()

Package "Product Management System 2" {
  Package "GUI Supplier Maintenance" {
    $SupplierMaintenance()
    $dmSuppliers()

    'Buttons
    $btSave()
    $btDelete()
    $btExit()
   
    'Relationships
    $uumf_associtarion($class1 = "SupplierMaintenance", $class2 = "btSave", $type="*-u-")
    $uumf_associtarion($class1 = "SupplierMaintenance", $class2 = "btDelete", $type="*-l-")
    $uumf_associtarion($class1 = "SupplierMaintenance", $class2 = "btExit", $type="*-r-")
    
    $uumf_associtarion($class1 = "SupplierMaintenance", $class2 = "dmSupplier", $type="*--")

    !$goal_l1 = "La ventana Supplier Maintenance está diseñada para"
    !$goal_l2 = "permitir a los usuarios gestionar los proveedores."
    !$goal_l3 = "Los usuarios pueden añadir, editar y eliminar"
    !$goal_l4 = "proveedores, así como visualizar detalles específicos"
    !$goal_l5 = "de cada proveedor."
    
    !$delimiter = '~'
    !$string = $goal_l1 + $delimiter + $goal_l2 + $delimiter + $goal_l3 + $delimiter + $goal_l4 + $delimiter + $goal_l5

    uumf_GUINote("N1", $string, $delimiter)
  }
  package DataLayer {
    class proveedores <<entity>> {
      - idSupplier :integer {PK} {not null}
      - name :string {not null}
      - address :string
      - email :string
      + insert()
      + update()
      + delete()
      + getsupplier(idSupplier :integer) recordSupplier
    }
  }

  $uumf_associtarion($class1 = "SupplierMaintenance", $class2 = "proveedores", $type="-->")
}



@enduml