@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
'skinparam linetype ortho
'skinparam linetype polyline

'Includes
!include https://raw.githubusercontent.com/egrpy/UUMF/main/50%20Sales%20System%20-%20Example/00%20Configurations/10%20Configurations.puml
$uumf_include()
$dictionary_include()

title CU Supplier Maintenance (System Design)

Package $systemName {
  Package "GUI Supplier Maintenance" {
    
    note as UIGoal
      La ventana Supplier Maintenance está diseñada para
      permitir a los usuarios gestionar los proveedores.
      Los usuarios pueden añadir, editar y eliminar
      proveedores, así como visualizar detalles específicos
      de cada proveedor.
    end note

    'Container
    $supplierMaintenance()

    'Data Models
    $dmSuppliers()

    'Buttons
    $btSave()
    $btDelete()
    $btExit()
   
    'Relationships
    $uumf_associtarion($class1 = "supplierMaintenance", $class2 = "btSave", $type="*-u-")
    $uumf_associtarion($class1 = "supplierMaintenance", $class2 = "btDelete", $type="*-l-")
    $uumf_associtarion($class1 = "supplierMaintenance", $class2 = "btExit", $type="*-r-")
    $uumf_associtarion($class1 = "supplierMaintenance", $class2 = "dmSupplier", $type="*--")
  }
  package DataLayer {
    $classSuppliers()
  }

  $uumf_associtarion($class1 = "supplierMaintenance", $class2 = "suppliers", $type="-r->")
}

@enduml